name: Deploy Supabase Edge Functions
on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main]
    paths: ['supabase/functions/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy to Develop
        run: |
          # Link to develop branch
          supabase link --project-ref sgieoyeaosgbzzxnzpxa
          
          # Deploy all functions
          supabase functions deploy groq-sales-filter
          supabase functions deploy psa-cert-lookup  
          supabase functions deploy countdown-pricing
          
          # List deployed functions
          supabase functions list
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}